name: Validate renovate config
permissions: {}

on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.38.0
      - run: ci-info run | sed "s/^export //" >> "$GITHUB_ENV"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: |
          grep -E "^[^/]+\.json$" "$CI_INFO_TEMP_DIR/pr_all_filenames.txt" | while read -r file; do
            if [ -f "$file" ]; then
              RENOVATE_CONFIG_FILE="$file" npx --package renovate -c renovate-config-validator
            fi
          done
